apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-zaak.fullname" . }}
  labels:
    {{- include "open-zaak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "open-zaak.selectorLabels" . | nindent 4 }}
{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-zaak.nginxFullname" . }}
  labels:
    {{- include "open-zaak.nginxLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
  selector:
    {{- include "open-zaak.nginxSelectorLabels" . | nindent 4 }}
{{- end }}
