apiVersion: v1
entries:
  open-zaak:
  - apiVersion: v2
    appVersion: 1.7.1
    created: "2023-05-16T17:57:40.6117647+02:00"
    dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      tags:
      - redis
      version: 17.10.2
    description: Productiewaardige API's voor Zaakgericht Werken
    digest: 922e8e3c7cd63ffd6f097e8806a8760d1c250b029274b5ae0c9055f3215237a7
    name: open-zaak
    type: application
    urls:
    - open-zaak-0.8.4.tgz
    version: 0.8.4
  - apiVersion: v2
    appVersion: 1.7.1
    created: "2023-05-16T17:57:40.6032533+02:00"
    dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      tags:
      - redis
      version: 17.10.2
    description: Productiewaardige API's voor Zaakgericht Werken
    digest: 51b1106efe3a1fc2f0d321d7bb084bb23848388145d2fe5ce02c0359ad6d3464
    name: open-zaak
    type: application
    urls:
    - open-zaak-0.8.3.tgz
    version: 0.8.3
  - apiVersion: v2
    appVersion: 1.7.1
    created: "2023-05-16T17:57:40.5942807+02:00"
    dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      tags:
      - redis
      version: 17.10.2
    description: Productiewaardige API's voor Zaakgericht Werken
    digest: f1b0e32974abce7daef56b577e1bb48be2f45305e53dda0231bece3f4027cec8
    name: open-zaak
    type: application
    urls:
    - open-zaak-0.8.2.tgz
    version: 0.8.2
  - apiVersion: v2
    appVersion: 1.7.1
    created: "2023-05-16T17:57:40.586016+02:00"
    dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      tags:
      - postgresql
      version: 12.4.2
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      tags:
      - redis
      version: 17.10.2
    description: Productiewaardige API's voor Zaakgericht Werken
    digest: e1a51cd442dcec1fd57200f4fe0c3e6d3abac126452414d4484414526b6e275e
    name: open-zaak
    type: application
    urls:
    - open-zaak-0.8.1.tgz
    version: 0.8.1
generated: "2023-05-16T17:57:40.5733317+02:00"
